### ISSUE TITLE
saya bikin landingpagenya

### ISSUE THREAD

**Issue by puterakahfi** [mazipan/awesome-js-dev-id#5]
@mazipan ini kalo di bikin model landingpage aja gimana ?

saya initiate projectnya terserah pake nuxtjs ato gridsome, tapi kalo saya lebih prefer ke gridsome. hehehe 

contohnya bisa di liat di sini mas 
https://codeigniter-id.github.io/

itu saya bikin pake gridsome

**Comment by mazipan** [comment]
Boleh mas @puterakahfi.
Bisa dicoba dulu di lokal, nanti PR aja ya.

**Comment by puterakahfi** [comment]
sudah saya initiate gridsomenya @mazipan 
https://puterakahfi.github.io/awesome-js-dev-id/

nanti tak coba explore lagi

**Comment by mazipan** [comment]
Daftarnya nanti disimpan di file statis JSON/JS biar gampang kalau mau nambah atau update.
Lebih keren lagi kalau bisa auto generate dari file readme.md yang sudah ada, mainan RegEx tapi :-(.

**Comment by puterakahfi** [comment]
bener  @mazipan  
ada beberapa opsi sih, pertama pake json static 
kedua pake markdown untuk query bisa pake graphql 
atau kombinasi keduanya, json buat indexnya aja, detailnya di markdown. 

untuk yg static json sudah saya implementasikan di sini

https://puterakahfi.github.io/nuxt-awesome/tutorials

**Comment by puterakahfi** [comment]
@mazipan  saya sudah update landingpagenya, maaf baru sempat karena ada pekerjaan lain 
sementara modelnya adalah json ( sebelumnya pake markdown, tapi ada kendala 
buat get data associative array, jadi pake json) 


data developer di simpan di directory content/devs/abjad -> developer akan di letakkan di sini sesuai abjadnya, satu developer satu file json

+ /content/devs
  + a
     - a-developer.json
     - ab-developername.json

untuk get data menggunakan graphql   

fitur searching  masih dalam tahap development 

update bisa dilihat di
https://puterakahfi.github.io/awesome-js-dev-id/


terima kasih

**Comment by mazipan** [comment]
Kabarin aja kalau sudah ready digunakan, nanti saya pinned di reponya juga.
Sekarang baru punya om Rian saja yang saya pinned, soalnya saya cek ini masih belum ready digunakan.

**Comment by puterakahfi** [comment]
> Kabarin aja kalau sudah ready digunakan, nanti saya pinned di reponya juga.
> Sekarang baru punya om Rian saja yang saya pinned, soalnya saya cek ini masih belum ready digunakan.

siap @mazipan , btw saya putuskan untuk memindahkan yang versi web ini ke repository sendiri, tapi tetap datanya diambil dari sini, data-data dari README saya pecah-pecah kedalam json file di dalam directory json sehinga web cuman ambil data saja 

secara fungsionalitas sudah bisa di gunakan ( fitur searching juga sudah bisa)tinggal proses ambil data readme untuk di convert ke json file. 

https://puterakahfi.github.io/jsid/
